#!/bin/sh
# postinst script for tn5250j

set -e

case "$1" in
    configure)
    update-desktop-database
    kbuildsycoca4 --noincremental    
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
